### PR TITLE
fix: add support for Scratch-style block comments

### LINKED ISSUE #3: Create custom comment icon that relies on the v11 CommentView (or RenderedWorkspaceComment)
- [ ] Decide which implementation is better - CommentView or RenderedWorkspaceComment

Dependent on v11 of Blockly Core, which includes the refactored Workspace Comment system.

### PR DESCRIPTION
**Pull request by gonfunko**
This PR adds support for Scratch-style block comments. These use the same look and feel as workspace comments, but are visually attached to their parent block by a line.

A new bubble, inheriting from the CommentView also used by workspace comments, is paired with a custom comment icon that replaces Blockly's built-in version. Additionally, custom events for all block comment actions (create, delete, modify, move, resize, collapse) are added and fired as needed, in order to keep the VM apprised of the state of the comments to allow it to properly serialize the project state when saving. The create, delete, and modify events are not undoable, because Blockly already handles undo support for those mutations via BlockChange events.

This fixes #3.

### CODE REVIEW

File: src/events_block_comment_base.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
+import * as Blockly from 'blockly/core';
```
Comment (BeksOmega) [inline src/events_block_comment_base.js]: Copyright heading, here and in other files.

File: src/events_block_comment_base.js [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+
+export class BlockCommentBase extends Blockly.Events.Abstract {
+  constructor(opt_blockComment) {
+    super();
+
+    this.isBlank = !opt_blockComment;
+    this.group = Blockly.Events.getGroup();
+    this.recordUndo = Blockly.Events.getRecordUndo();
```
Comment (BeksOmega) [inline src/events_block_comment_base.js]: This is handled by the base class, can be deleted.

File: src/events_block_comment_change.js [hunk 3]
```diff
@@ -0,0 +1,34 @@
+import * as Blockly from 'blockly/core';
+import {BlockCommentBase} from './events_block_comment_base.js';
+
+class BlockCommentChange extends BlockCommentBase {
+  constructor(opt_blockComment, oldContents, newContents) {
+    super(opt_blockComment);
+    this.type = 'block_comment_change';
+    this.oldContents_ = oldContents;
+    this.newContents_ = newContents;
+    this.recordUndo = false;
```
Comment (BeksOmega) [inline src/events_block_comment_change.js:19]: Can you add a comment here and in other places about why `recordUndo` is false so that future peoples can know what's going on?

File: src/scratch_comment_bubble.js [hunk 4]
```diff
@@ -0,0 +1,140 @@
+import * as Blockly from 'blockly/core';
+
+export class ScratchCommentBubble extends Blockly.comments.CommentView {
```
Comment (BeksOmega) [inline src/scratch_comment_bubble.js:14]: Maybe add some `@implements` JSDoc to give hints to future people about which interfaces we're using? (and make this easier to convert to typescript if we want to)

File: src/scratch_comment_bubble.js [hunk 5]
```diff
@@ -0,0 +1,140 @@
...
+    this.getSvgRoot().setAttribute(
+        'style', `--colour-commentBorder: ${sourceBlock.getColourTertiary()};`);
+
+    Blockly.browserEvents.conditionalBind(
+      this.getSvgRoot(),
+      'pointerdown',
+      this,
+      this.startGesture,
+    );
+    // Don't zoom with mousewheel; let it scroll instead.
```
Comment (BeksOmega) [inline src/scratch_comment_bubble.js:31]: Why is this a problem in Scratch? In core the workspace comments scroll just fine. Wondering if the event listeners are actually messed up somewhere else, which is causing this problem.

File: src/scratch_comment_bubble.js [hunk 6]
```diff
@@ -0,0 +1,140 @@
...
+
+  isMovable() {
+    return true;
+  }
+
+  moveDuringDrag(newLocation) {
+    this.moveTo(newLocation);
+  }
+
+  moveTo(xOrCoordinate, y) {
```
Comment (BeksOmega) [inline src/scratch_comment_bubble.js:56]: Ah darn, I didn't realize there was a signature conflict between different versions of `moveTo` :/ That's my bad.

File: src/scratch_comment_bubble.js [hunk 7]
```diff
@@ -0,0 +1,140 @@
...
+    this.workspace.getLayerManager()?.moveToDragLayer(this);
+    Blockly.utils.dom.addClass(this.getSvgRoot(), 'blocklyDragging');
+  }
+
+  drag(newLocation, event) {
+    this.moveTo(newLocation);
+  }
+
+  endDrag() {
+    this.workspace.getLayerManager()?.moveOffDragLayer(this, 100);
```
Comment (BeksOmega) [inline src/scratch_comment_bubble.js]: This should use the [BUBBLE](https://github.com/google/blockly/blob/293bb7c182fd5905847cb7470dc373fe2dc3c55b/core/layers.ts#L19) constant instead (we also need to actually export that from core).

File: src/scratch_comment_icon.js [hunk 8]
```diff
@@ -0,0 +1,221 @@
...
+  }
+
+  async setBubbleVisible(visible) {
+    this.commentBubble.setCollapsed(!visible);
+  }
+
+  dispose() {
+    this.commentBubble?.removeTextChangeListener(this.onTextChangedListener);
+    this.commentBubble?.removeSizeChangeListener(this.onSizeChangedListener);
+    this.commentBubble?.removeOnCollapseListener(this.onCollapseListener);
```
Comment (BeksOmega) [inline src/scratch_comment_icon.js]: You shouldn't need to unregister these since JS uses mark-and-sweep. Once the icon is dereferenced, anything that was referenced through the icon will get collected.

File: src/scratch_comment_icon.js [hunk 9]
```diff
@@ -0,0 +1,221 @@
...
+    this.commentBubble?.dispose();
```
Comment (BeksOmega) [inline src/scratch_comment_icon.js:183]: This is necessary though since it's removing stuff from the DOM.

File: src/scratch_comment_icon.js [hunk 10]
```diff
@@ -0,0 +1,221 @@
...
+    this.onTextChangedListener = this.onTextChanged.bind(this);
+    this.onSizeChangedListener = this.onSizeChanged.bind(this);
+    this.onCollapseListener = this.onCollapsed.bind(this);
+    this.commentBubble.addTextChangeListener(this.onTextChangedListener);
+    this.commentBubble.addSizeChangeListener(this.onSizeChangedListener);
+    this.commentBubble.addOnCollapseListener(this.onCollapseListener);
+    this.repositionAfterRender = true;
+
+    // We need to force a render of our parent block and wait for it to complete, because at this
+    // point, we don't know our own position (needed to calculate the anchor point and position
```
Comment (BeksOmega) [inline src/scratch_comment_icon.js]: I'm a bit confused about what's going on here - might be better to talk synchronously about this. Who is "we" in "we don't know our own position"?

File: src/scratch_comment_icon.js [hunk 11]
```diff
@@ -0,0 +1,221 @@
...
+    const sourceBlockOrigin = this.sourceBlock.getRelativeToSurfaceXY();
+    let left;
+    let right;
+    if (this.sourceBlock.RTL) {
+      left = sourceBlockOrigin.x - this.sourceBlock.width;
+      right = sourceBlockOrigin.x;
+    } else {
+      left = sourceBlockOrigin.x;
+      right = sourceBlockOrigin.x + this.sourceBlock.width;
+    }
```
Comment (BeksOmega) [inline src/scratch_comment_icon.js]: This looks like it's in workspace coordinates? in which case you can use `getBoundingRectangle`

File: src/scratch_comment_icon.js [hunk 12]
```diff
@@ -0,0 +1,221 @@
...
+  onLocationChange(blockOrigin) {
+    const initialLocation = this.workspaceLocation;
+    super.onLocationChange(blockOrigin);
+    const newLocation = this.workspaceLocation;
+
+    if (this.commentBubble) {
+      const oldBubbleLocation = this.commentBubble.getRelativeToSurfaceXY();
+      const delta = Blockly.utils.Coordinate.difference(newLocation, initialLocation);
+      const newBubbleLocation = Blockly.utils.Coordinate.sum(oldBubbleLocation, delta);
+      this.commentBubble.moveTo(newBubbleLocation);
```
Comment (BeksOmega) [inline src/scratch_comment_icon.js]: Could we let the bubble move itself based on `setAnchorLocation` instead of calling `moveTo` explicitly? That is how the other bubbles work iirc

File: src/scratch_comment_icon.js [hunk 13]
```diff
@@ -0,0 +1,221 @@
...
+      ),
+    );
+  }
+
+  getBubbleLocation() {
+    return this.commentBubble?.getRelativeToSurfaceXY();
+  }
+
+  saveState() {
+    if (this.commentBubble) {
```
Comment (BeksOmega) [inline src/scratch_comment_icon.js]: Can you use an early return here instead?

File: src/scratch_comment_icon.js (hunk 11 above)
Comment (gonfunko) [reply src/scratch_comment_icon.js]: `getBoundingRectangle` doesn't work because it includes subsequent blocks, and we need the actual rect of this block alone to determine the vertical midpoint for the anchor line to emanate from.

File: src/scratch_comment_icon.js (hunk 10 above)
Comment (gonfunko) [reply src/scratch_comment_icon.js]: "We" is the icon here, but yeah happy to chat offline. This behavior was surprisingly and possibly technically a bug, but it's as described in the comment - the icon gets instantiated before the block it's attached to is fully laid out/rendered/initialized.

File: src/scratch_comment_bubble.js (hunk 5 above)
Comment (gonfunko) [reply src/scratch_comment_bubble.js:31]: It works in core because I stole this from core: https://github.com/google/blockly/blob/17dfa462a357b553523393145c9d5045023e627b/core/comments/rendered_workspace_comment.ts#L69-L77

File: src/scratch_comment_bubble.js (hunk 6 above)
Comment (gonfunko) [reply src/scratch_comment_bubble.js:56]: No worries! Might be nice to clean up some time in the future, but not sure it's worth a breaking change.

File: src/scratch_comment_bubble.js (hunk 5 above)
Comment (BeksOmega) [reply src/scratch_comment_bubble.js:31]: Ah, well fair enough lol

File: src/events_block_comment_base.js (hunk 1 above)
Comment (gonfunko) [reply src/events_block_comment_base.js]: Done

File: src/events_block_comment_base.js (hunk 2 above)
Comment (gonfunko) [reply src/events_block_comment_base.js]: Done

File: src/events_block_comment_change.js (hunk 3 above)
Comment (gonfunko) [reply src/events_block_comment_change.js:19]: Done

File: src/scratch_comment_bubble.js (hunk 4 above)
Comment (gonfunko) [reply src/scratch_comment_bubble.js:14]: Done

File: src/scratch_comment_bubble.js (hunk 7 above)
Comment (gonfunko) [reply src/scratch_comment_bubble.js]: Done

File: src/scratch_comment_icon.js (hunk 8 above)
Comment (gonfunko) [reply src/scratch_comment_icon.js]: Done

File: src/scratch_comment_icon.js (hunk 10 above)
Comment (gonfunko) [reply src/scratch_comment_icon.js]: Cleaned this up!

File: src/scratch_comment_icon.js (hunk 11 above)
Comment (gonfunko) [reply src/scratch_comment_icon.js]: Updated this to use the newly introduced `getBoundingRectangleWithoutChildren()`.

File: src/scratch_comment_icon.js (hunk 12 above)
Comment (gonfunko) [reply src/scratch_comment_icon.js]: Done

File: src/scratch_comment_icon.js (hunk 13 above)
Comment (gonfunko) [reply src/scratch_comment_icon.js]: Done

File: src/scratch_comment_bubble.js [hunk 14]
```diff
@@ -0,0 +1,169 @@
...
+        y2: 16,
+        style: `stroke: ${this.sourceBlock.getColourTertiary()}; stroke-width: 1`,
+      },
+      this.getSvgRoot()
+    );
+    this.getSvgRoot().insertBefore(
+      this.anchorChain,
+      this.getSvgRoot().firstChild
+    );
+    this.redrawAnchorChain();
```
Comment (BeksOmega) [inline src/scratch_comment_bubble.js]: Is it necessary to redraw immediately?

File: src/scratch_comment_bubble.js [hunk 15]
```diff
@@ -0,0 +1,169 @@
...
+      this.dropAnchor();
+    } else {
+      const oldLocation = this.getRelativeToSurfaceXY();
+      const delta = Blockly.utils.Coordinate.difference(this.anchor, oldAnchor);
+      const newLocation = Blockly.utils.Coordinate.sum(oldLocation, delta);
+      this.moveTo(newLocation);
+    }
+  }
+
+  dropAnchor() {
```
Comment (BeksOmega) [inline src/scratch_comment_bubble.js:117]: Love this name haha.

File: src/scratch_comment_bubble.js [hunk 16]
```diff
@@ -0,0 +1,169 @@
...
+
+  isMovable() {
+    return true;
+  }
+
+  moveDuringDrag(newLocation) {
+    this.moveTo(newLocation);
+  }
+
+  moveTo(xOrCoordinate, y) {
```
Comment (BeksOmega) [inline src/scratch_comment_bubble.js:56]: Should we be firing move events from here? or only from the `endDrag` method?

[Edit: ah wait, the events are also being fire from `setBubbleLocation` so maybe fine?]

File: src/events_block_comment_move.js [hunk 17]
```diff
@@ -0,0 +1,60 @@
...
+    this.newCoordinate_ = newCoordinate;
+  }
+
+  toJson() {
+    return {
+      ...super.toJson(),
+      newCoordinate: {
+        x: this.newCoordinate_.x,
+        y: this.newCoordinate_.y,
+      },
```
Comment (BeksOmega) [inline src/events_block_comment_move.js]: Can this just be `newCoordinate: this.newCoordinate_`?

File: src/events_block_comment_resize.js [hunk 18]
```diff
@@ -0,0 +1,58 @@
...
+    this.newSize = newSize;
+  }
+
+  toJson() {
+    return {
+      ...super.toJson(),
+      newSize: {
+        width: this.newSize.width,
+        height: this.newSize.height,
+      },
```
Comment (BeksOmega) [inline src/events_block_comment_resize.js]: Similarly here, `newSize: this.newSize`?

**Review by BeksOmega — COMMENTED** [review]
The positioning logic is much more grokable now! Just a few more Qs/nits then should be gtg

File: src/scratch_comment_bubble.js (hunk 14 above)
Comment (gonfunko) [reply src/scratch_comment_bubble.js]: Nope, adjusted the initial attributes of the anchor chain and removed the redraw.

File: src/scratch_comment_bubble.js (hunk 15 above)
Comment (gonfunko) [reply src/scratch_comment_bubble.js:117]: It's probably too clever for its own good, but eh...

File: src/scratch_comment_bubble.js (hunk 16 above)
Comment (gonfunko) [reply src/scratch_comment_bubble.js:56]: Yeah as you noted this should be fine, and firing them (and making the VM update its state) continuously during a drag seems excessive.

File: src/events_block_comment_resize.js (hunk 18 above)
Comment (gonfunko) [reply src/events_block_comment_resize.js]: Done

File: src/events_block_comment_move.js (hunk 17 above)
Comment (gonfunko) [reply src/events_block_comment_move.js]: Done

**Review by BeksOmega — APPROVED** [review]
