### PR TITLE
fix: fix styling of dropdown menus

### LINKED ISSUE #98: The dropdown field and the option should be displayed with a slightly lighter background color, uses bold text in the menu similar to Scratch
The dropdown field and the option should be displayed with a slightly lighter background color, uses bold text in the menu, and does not display a darkened selection indicator as per Scratch.

Image

As per Scratch:

Image

### PR DESCRIPTION
**Pull request by gonfunko**
This PR aligns the styling of dropdown menus with Scratch. This fixes #98. Specifically:

* Dropdown menus take the color of the main block, not the shadow block from whence they spawn
* Shadow dropdown block colors are correct/identical to Scratch, where they had been slightly off
* Removed the white outline on hover on non-shadow dropdown fields
* Where dropdown menu block definitions are being patched by scratch-gui, the no-op block definitions have been removed here

This PR also depends on the related https://github.com/gonfunko/scratch-gui/pull/22.

### CODE REVIEW

File: src/blocks/control.js [hunk 1]
```diff
@@ -383,22 +383,9 @@ Blockly.Blocks["control_start_as_clone"] = {
 
 Blockly.Blocks["control_create_clone_of_menu"] = {
   /**
-   * Create-clone drop-down menu.
+   * Create-clone drop-down menu. Populated dynamically by scratch-gui.
```
Comment (rachel-fenichel) [inline src/blocks/control.js]: If this is going to be created by scratch-gui, and is unusable without scratch-gui code running, it seems better to not add it to `Blockly.Blocks` at all, and make scratch-gui responsible for that as well.

Comment (rachel-fenichel) [reply src/blocks/control.js]: Even if you want to keep these, you don't need the `@this` anymore, and can therefore move the comment to above `Blockly.Blocks["name"] = {};` and compress the declaration down to a single line.

File: src/colours.js [hunk 2]
```diff
@@ -155,6 +155,22 @@ const Colours = {
       }
     }
   },
+  registerBlockStyles: function () {
```
Comment (rachel-fenichel) [inline src/colours.js]: As I understand it, this finds all of the block styles in `cssColours` (where a block style has a `primary` property) and creates a corresponding stanza in the current Blockly theme.

I think it would be better to [create a new theme](https://developers.google.com/blockly/guides/configure/web/appearance/themes) based on the `zelos` theme and add these colours to it before injection. That way you aren't relying on modifying an object that's already in use, and you can pass the correct theme into the call to `inject`.

**Review by rachel-fenichel — APPROVED** [review]

File: src/colours.js (hunk 2 above)
Comment (gonfunko) [reply src/colours.js]: Done!

File: src/blocks/control.js (hunk 1 above)
Comment (gonfunko) [reply src/blocks/control.js]: Condensed them accordingly; I think ultimately I'd like to pass a reference to the VM into scratch-blocks so that all the definitions can be here.

**Review by rachel-fenichel — APPROVED** [review]
