### PR TITLE
fix: fix positioning of categories when scrolling via the toolbox

### LINKED ISSUE #151: Category label is offset too far from the top of the flyout when clicking a category in the toolbox
When clicking a toolbox category, the flyout scrolls to show that category but with a bit too much space before the category's label in the flyout:

Screenshot 2024-08-29 at 1 46 23 PM

### PR DESCRIPTION
**Pull request by gonfunko**
This PR fixes #151 to avoid having too much space atop category labels when jumping to a category via the toolbox.

### CODE REVIEW

File: src/checkable_continuous_flyout.js [hunk 1]
```diff
@@ -103,6 +103,21 @@ export class CheckableContinuousFlyout extends ContinuousFlyout {
     this.checkboxes_.clear();
   }
 
+  layout_(contents, gaps) {
+    super.layout_(contents, gaps);
+    // We want large gaps between categories (see GAP_Y), but don't want those
+    // counted as part of the category for purposes of scrolling to show the
+    // category, so we reset/adjust the label gaps used for the scroll position
+    // calculation here.
+    this.labelGaps.fill(4);
```
Comment (rachel-fenichel) [inline src/checkable_continuous_flyout.js]: Express these in terms of GRID_UNIT if possible (here and below)

**Review by rachel-fenichel — CHANGES_REQUESTED** [review]

File: src/checkable_continuous_flyout.js (hunk 1 above)
Comment (gonfunko) [reply src/checkable_continuous_flyout.js]: Done

**Review by rachel-fenichel — APPROVED** [review]
