### PR TITLE
fix: Add support for flyout labels with status indicators

### LINKED ISSUE #7: Implement extension category headers

### PR DESCRIPTION
**Pull request by gonfunko**
This PR adds a FlyoutButton subclass that adds a status indicator icon, along with an associated inflater. The toolbox and category are also updated to populate these in the intermediate representation of the flyout contents, because the continuous toolbox synthesizes labels for each toolbox category and injects them in between the blocks for each category. This fixes #7.

### CODE REVIEW

File: src/status_indicator_label.js [hunk 1]
```diff
@@ -39,121 +36,129 @@ goog.require('Blockly.FlyoutButton');
  * @extends {Blockly.FlyoutButton}
  * @constructor
  */
-Blockly.FlyoutExtensionCategoryHeader = function(workspace, targetWorkspace, xml) {
+export class StatusIndicatorLabel extends Blockly.FlyoutButton {
+  extensionId;
```
Comment (rachel-fenichel) [inline src/status_indicator_label.js:38]: Add doc.

**Review by rachel-fenichel — APPROVED** [review]
LGTM once you add docs in `status_indicator_label.js`

File: src/status_indicator_label.js (hunk 1 above)
Comment (gonfunko) [reply src/status_indicator_label.js:38]: Done
